// <auto-generated />
using System;
using Argonauts.Infrastructure.Database.Repository.DataSources;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspNetApp.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260515185520_Add_Email_to_Player")]
    partial class Add_Email_to_Player
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Balance", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<int>("Quants")
                        .HasColumnType("integer");

                    b.HasKey("OwnerId");

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Galaxy", b =>
                {
                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Version"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Version");

                    b.ToTable("Galaxies");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Login");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Spaceship", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("GalaxyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("LocatedAngleMilliradians")
                        .HasColumnType("integer");

                    b.Property<int>("LocatedRadius")
                        .HasColumnType("integer");

                    b.HasKey("OwnerId");

                    b.HasIndex("GalaxyVersion");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.SpaceshipCondition", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Antimatter")
                        .HasColumnType("integer");

                    b.Property<int>("Durability")
                        .HasColumnType("integer");

                    b.Property<int>("Energy")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAntimatter")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDistance")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDurability")
                        .HasColumnType("integer");

                    b.Property<int>("MaxEnergy")
                        .HasColumnType("integer");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.HasKey("OwnerId");

                    b.ToTable("SpaceshipConditions");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.SpaceshipStarVisit", b =>
                {
                    b.Property<Guid>("SpaceshipId")
                        .HasColumnType("uuid");

                    b.Property<int>("StarGalaxyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("StarRadius")
                        .HasColumnType("integer");

                    b.Property<int>("StarAngleMilliradians")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VisitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SpaceshipId", "StarGalaxyVersion", "StarRadius", "StarAngleMilliradians");

                    b.HasIndex("StarGalaxyVersion", "StarRadius", "StarAngleMilliradians");

                    b.ToTable("SpaceshipStarVisits");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Star", b =>
                {
                    b.Property<int>("GalaxyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Radius")
                        .HasColumnType("integer");

                    b.Property<int>("AngleMilliradians")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("-");

                    b.HasKey("GalaxyVersion", "Radius", "AngleMilliradians");

                    b.HasIndex("GalaxyVersion", "Radius", "AngleMilliradians")
                        .IsUnique();

                    b.ToTable("Stars");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Balance", b =>
                {
                    b.HasOne("Argonauts.Infrastructure.Database.Entity.Spaceship", "Spaceship")
                        .WithOne("Balance")
                        .HasForeignKey("Argonauts.Infrastructure.Database.Entity.Balance", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spaceship");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Spaceship", b =>
                {
                    b.HasOne("Argonauts.Infrastructure.Database.Entity.Galaxy", "Galaxy")
                        .WithMany()
                        .HasForeignKey("GalaxyVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Argonauts.Infrastructure.Database.Entity.Player", "Owner")
                        .WithOne("Spaceship")
                        .HasForeignKey("Argonauts.Infrastructure.Database.Entity.Spaceship", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Galaxy");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.SpaceshipCondition", b =>
                {
                    b.HasOne("Argonauts.Infrastructure.Database.Entity.Spaceship", "Spaceship")
                        .WithOne("SpaceshipCondition")
                        .HasForeignKey("Argonauts.Infrastructure.Database.Entity.SpaceshipCondition", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spaceship");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.SpaceshipStarVisit", b =>
                {
                    b.HasOne("Argonauts.Infrastructure.Database.Entity.Spaceship", "Spaceship")
                        .WithMany("VisitedStars")
                        .HasForeignKey("SpaceshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Argonauts.Infrastructure.Database.Entity.Star", "Star")
                        .WithMany("VisitedByShips")
                        .HasForeignKey("StarGalaxyVersion", "StarRadius", "StarAngleMilliradians")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spaceship");

                    b.Navigation("Star");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Star", b =>
                {
                    b.HasOne("Argonauts.Infrastructure.Database.Entity.Galaxy", "Galaxy")
                        .WithMany("Stars")
                        .HasForeignKey("GalaxyVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Galaxy");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Galaxy", b =>
                {
                    b.Navigation("Stars");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Player", b =>
                {
                    b.Navigation("Spaceship");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Spaceship", b =>
                {
                    b.Navigation("Balance");

                    b.Navigation("SpaceshipCondition");

                    b.Navigation("VisitedStars");
                });

            modelBuilder.Entity("Argonauts.Infrastructure.Database.Entity.Star", b =>
                {
                    b.Navigation("VisitedByShips");
                });
#pragma warning restore 612, 618
        }
    }
}
