// <auto-generated />
using System;
using Argonauts.Infrastructure.Database.Repository.DataSources;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspNetApp.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260320182705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.Galaxy", b =>
                {
                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Version"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Version");

                    b.ToTable("Galaxies");
                });

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.Spaceship", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("GalaxyVersion")
                        .HasColumnType("integer");

                    b.Property<double>("LocatedAngle")
                        .HasColumnType("double precision");

                    b.Property<int>("LocatedRadius")
                        .HasColumnType("integer");

                    b.HasKey("OwnerId");

                    b.HasIndex("GalaxyVersion");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.SpaceshipStarVisit", b =>
                {
                    b.Property<Guid>("SpaceshipId")
                        .HasColumnType("uuid");

                    b.Property<int>("StarGalaxyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("StarRadius")
                        .HasColumnType("integer");

                    b.Property<double>("StarAngle")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("VisitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SpaceshipId", "StarGalaxyVersion", "StarRadius", "StarAngle");

                    b.HasIndex("StarGalaxyVersion", "StarRadius", "StarAngle");

                    b.ToTable("SpaceshipStarVisits");
                });

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.Star", b =>
                {
                    b.Property<int>("GalaxyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Radius")
                        .HasColumnType("integer");

                    b.Property<double>("Angle")
                        .HasColumnType("double precision");

                    b.HasKey("GalaxyVersion", "Radius", "Angle");

                    b.HasIndex("GalaxyVersion", "Radius", "Angle")
                        .IsUnique();

                    b.ToTable("Stars");
                });

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.Spaceship", b =>
                {
                    b.HasOne("AspNetApp.Repository.DbEntity.Galaxy", "Galaxy")
                        .WithMany()
                        .HasForeignKey("GalaxyVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetApp.Repository.DbEntity.Player", "Owner")
                        .WithOne("Spaceship")
                        .HasForeignKey("AspNetApp.Repository.DbEntity.Spaceship", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Galaxy");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.SpaceshipStarVisit", b =>
                {
                    b.HasOne("AspNetApp.Repository.DbEntity.Spaceship", "Spaceship")
                        .WithMany("VisitedStars")
                        .HasForeignKey("SpaceshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetApp.Repository.DbEntity.Star", "Star")
                        .WithMany("VisitedByShips")
                        .HasForeignKey("StarGalaxyVersion", "StarRadius", "StarAngle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spaceship");

                    b.Navigation("Star");
                });

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.Star", b =>
                {
                    b.HasOne("AspNetApp.Repository.DbEntity.Galaxy", "Galaxy")
                        .WithMany("Stars")
                        .HasForeignKey("GalaxyVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Galaxy");
                });

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.Galaxy", b =>
                {
                    b.Navigation("Stars");
                });

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.Player", b =>
                {
                    b.Navigation("Spaceship");
                });

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.Spaceship", b =>
                {
                    b.Navigation("VisitedStars");
                });

            modelBuilder.Entity("AspNetApp.Repository.DbEntity.Star", b =>
                {
                    b.Navigation("VisitedByShips");
                });
#pragma warning restore 612, 618
        }
    }
}
